# Generated by Django 4.1.3 on 2022-11-23 10:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readonly', models.BooleanField(default=False)),
                ('maintenance', models.BooleanField(default=False)),
                ('down', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'mode',
                'verbose_name_plural': 'mode',
                'db_table': 'mode',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('paytm_merchant_id', models.CharField(blank=True, max_length=128, null=True)),
                ('paytm_merchant_key', models.CharField(blank=True, max_length=128, null=True)),
                ('paytm_sales_wallet_guid', models.CharField(blank=True, max_length=128, null=True)),
                ('paytm_merchant_guid', models.CharField(blank=True, max_length=128, null=True)),
                ('paytm_cashback_wallet_guid', models.CharField(blank=True, max_length=128, null=True)),
                ('paytm_cashback_merchant_guid', models.CharField(blank=True, max_length=128, null=True)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('bank_transfer_minimum_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('referal_bonus', models.DecimalField(decimal_places=3, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('invitation_code_length', models.PositiveIntegerField(default=0)),
                ('invitation_usage_limit', models.PositiveIntegerField(default=0)),
                ('referral_for_both', models.BooleanField(default=False)),
                ('total_invitation', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'settings',
                'verbose_name_plural': 'settings',
                'db_table': 'main_settings',
                'ordering': ('id',),
            },
        ),
    ]
